### ISSUE TITLE
About error reporting

### ISSUE THREAD

**Issue by haifenghuang** [vassilych/cscs#20]
I'm reading your book `Implementing a custom language succinctly`. What I wished is a language which have much error reporting functionality. When users write a `bad` cscs file and run them, they want to know where the errors come from. I think that's very import for the cscs script users.

Could you please give some hints on how to implement this functionality?

It's much better if you could add this functionality to the source.

**Comment by vassilych** [comment]
Hi there,

Yes indeed, completely agree that error reporting is one of the most
important parts.
I started adding it, inclusive mentioning exactly where the error occurs.
It's not done yet, but you can see how I do it in the implementation of the
Utils.ThrowErrorMsg() method.

**Comment by haifenghuang** [comment]
Thanks a lot. I'll have a look.
