### ISSUE TITLE
Is it worth learning cscs for developing MathJaX-like LaTeX renderer?

### ISSUE THREAD

**Issue by pstricks-fans** [vassilych/cscs#22]
I am interested to render TeX mathematics equation on Unity game engine like TeXDraw as well as on web browsers like MathJaX. 

Is it worth learning cscs for developing TeX renderers above? Or I am in a wrong learning path?

**Comment by vassilych** [comment]
Hi there, yes I think it's a good idea and of course possible.
Here is an article on using CSCS in Unity:
https://www.codemag.com/Article/1903081/Using-Custom-Scripting-and-Modding-in-Unity-Game-and-App-Development
Let me know if you have more specific questions.

**Comment by pstricks-fans** [comment]
Hi Vassilych, thank you for your quick response.

Actually I want to shorten my learning path.  
I want to create a new MathJaX or KaTeX like renders for learning purposes.

It is very hard to understand the following code: [KaTeX's parser.js](https://github.com/KaTeX/KaTeX/blob/master/src/Parser.js)


Do you have any advice about this? Split and Merge algorithm is still relevant here?
