### ISSUE TITLE
how to debug cscs file?

### ISSUE THREAD

**Issue by BenDerPan** [vassilych/cscs#23]
Hi, thx for your great job, and I have two questions about how to  debug cscs script:
1. how to setup the vscode to make debugger work? 
2. if I want to make a custom winform debugger tool for cscs, simplely support insert breakpoints, watch the variables , step in/out, any help to do that?

**Comment by vassilych** [comment]
Hi, Ben, this is very interesting. What is your project about and what it
would do at the end?

Here is the link on how to set it the VS Code Extension up and connect it
to the server running the CSCS:

https://marketplace.visualstudio.com/items?itemName=vassilik.cscs-debugger

The CSCS Debugger VS Code is open source, I do exactly that, breakpoints,
watch variables, etc.
The CSCS Debugger source code is at
https://github.com/vassilych/cscs-debugger

And the actual CSCS code, where the Debuggers is listening for the VS Code
Extension is here:
https://github.com/vassilych/cscs

Best of luck and let me know how it is going!
Vassili

**Comment by BenDerPan** [comment]
I'm trying to use it as a backend for a visual programming language(such as [Snap](https://github.com/jmoenig/Snap), and people can program with the internal APIs（like function in cscs) to simplify the programming part, I think [node-red](https://github.com/node-red/node-red) is a nice start, if we can combine cscs with blazor, maybe it's another surprise,  it's just a simple idea right now :)

**Comment by vassilych** [comment]
Ok you can contact me via my private email so that we can discuss it.
vassilik at gmail

**Comment by BenDerPan** [comment]
thx， I'm going to take some time to do some research on it, and I'd be happy to share it with you。
close this issue now. :)
